<?php

/**
 * ContextPulse - Immutable signed pulse DTO generated by PulseGenerator.
 *
 * PROVISIONAL: This DTO is a mirror of the canonical definition owned by
 * sparxstar-ouroboros-integrity. Replace this file with the Ouroboros package
 * import once that package ships.
 *
 * Hard rule: ContextPulse NEVER contains identity claims.
 * The identity_id MUST NOT appear in any ContextPulse payload.
 *
 * @package Starisian\Sparxstar\Sirus
 */

declare(strict_types=1);

namespace Starisian\Sparxstar\Sirus\dto;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Immutable value object representing a signed context pulse.
 *
 * A ContextPulse is a short-lived, tamper-evident assertion of non-identity
 * context (device, session, trust) that downstream services can verify without
 * contacting Sirus again. HMAC-SHA256 signature is included as the `sig` field.
 *
 * Pulse NEVER contains identity claims — identity_id is always excluded.
 */
final readonly class ContextPulse
{
    /**
     * @param string $pulse_id   Unique pulse identifier (UUID v4).
     * @param string $context_id The context_id this pulse was issued for.
     * @param string $device_id  The device this pulse was issued for.
     * @param string $session_id The session this pulse was issued for.
     * @param string $site_id    The site at the time of pulse generation.
     * @param string $network_id The network at the time of pulse generation.
     * @param float  $trust_score Resolved trust score [0.0, 1.0].
     * @param string $trust_level Resolved trust level string.
     * @param int    $issued_at  Unix timestamp of pulse creation.
     * @param int    $expires    Unix timestamp of pulse expiry.
     * @param string $sig        HMAC-SHA256 signature over the canonical payload.
     */
    public function __construct(
        public string $pulse_id,
        public string $context_id,
        public string $device_id,
        public string $session_id,
        public string $site_id,
        public string $network_id,
        public float  $trust_score,
        public string $trust_level,
        public int    $issued_at,
        public int    $expires,
        public string $sig,
    ) {
    }

    /**
     * Creates a ContextPulse from a raw array (e.g. from JSON decode).
     *
     * @param array<string, mixed> $data Raw pulse data.
     * @throws \InvalidArgumentException If required fields are missing or invalid.
     */
    public static function fromArray(array $data): self
    {
        $required = ['pulse_id', 'context_id', 'device_id', 'session_id', 'site_id',
                     'network_id', 'trust_score', 'trust_level', 'issued_at', 'expires', 'sig'];

        foreach ($required as $key) {
            if (! array_key_exists($key, $data)) {
                throw new \InvalidArgumentException(
                    '[Sirus] ContextPulse::fromArray() missing required field: ' . $key
                );
            }
        }

        return new self(
            pulse_id:    (string) $data['pulse_id'],
            context_id:  (string) $data['context_id'],
            device_id:   (string) $data['device_id'],
            session_id:  (string) $data['session_id'],
            site_id:     (string) $data['site_id'],
            network_id:  (string) $data['network_id'],
            trust_score: (float)  $data['trust_score'],
            trust_level: (string) $data['trust_level'],
            issued_at:   (int)    $data['issued_at'],
            expires:     (int)    $data['expires'],
            sig:         (string) $data['sig'],
        );
    }

    /**
     * Returns the pulse as an associative array for serialization.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'pulse_id'    => $this->pulse_id,
            'context_id'  => $this->context_id,
            'device_id'   => $this->device_id,
            'session_id'  => $this->session_id,
            'site_id'     => $this->site_id,
            'network_id'  => $this->network_id,
            'trust_score' => $this->trust_score,
            'trust_level' => $this->trust_level,
            'issued_at'   => $this->issued_at,
            'expires'     => $this->expires,
            'sig'         => $this->sig,
        ];
    }
}
